version: "3.3"

services: 
  my-mysql: 
    image: mysql:latest
    ports:  
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=my-secret-pw  
  
  api: 
    image: nginx:1.12-alpine